# Generated by Django 4.2.3 on 2023-07-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Please Inter Name student ', max_length=30)),
                ('age', models.IntegerField()),
                ('img', models.ImageField(upload_to='ipone%y%m%d')),
            ],
        ),
    ]
