# Generated by Django 4.2.3 on 2023-07-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='ipone-%y/%m/%d'),
        ),
    ]
